Work section and about section
ntimanu/Portfolio pull request #2
Opened 2023-04-27 20:22 UTC by ntimanu

In this project we:

- Added Work section
- Added About section

2023-04-27 21:00 UTC, Kamba56 requested changes
Hi @ntimanu, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great job using grid and flexbox to layout contents of page👏👏👏
- [x] Great job sticking to design guidelines

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 21:00 UTC, Kamba56 commented on index.html
> +          <button class="btntxt">See Project</button>
- [x] Great job adding the hover and active state on your buttons. I noticed that your button's background color doesn't properly match the Figma template. You are expected to stick to design as much as possible and this includes colors and backgrounds. Kindly fix this, please.
### Your design
![image](https://user-images.githubusercontent.com/94551484/234987746-443134bb-9712-472f-9147-35832bf17e33.png)
### FIgma
![image](https://user-images.githubusercontent.com/94551484/234987841-0ed1514f-8713-40ec-8a5a-1d092841bfda.png)

2023-04-27 21:12 UTC, ntimanu commented on index.html
> +          <button class="btntxt">See Project</button>
Done

2023-04-28 00:28 UTC, BregornOriginal approved these changes
Hi @ntimanu 

Your project is complete!  There is nothing else to say other than... it's time to merge it

Congratulations! 

![giphy (7)](https://user-images.githubusercontent.com/93630700/235022342-947b1c25-ed0b-4d25-a937-731bb72afd02.gif)

## Highlights

✅ Linters are passing
✅ Excellent commit history 🥇 


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-04-28 09:25 UTC, merged